name: Build A30s Kernel

on:
  workflow_dispatch: # Lets you trigger it manually

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev make gcc clang wget git ccache

      - name: Download ARM64 GCC
        run: |
          mkdir -p toolchain
          cd toolchain
          wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20230715.tar.gz
          tar -xf 20230715.tar.gz
          mv proton-clang-* proton-clang

      - name: Build Kernel
        run: |
          export PATH=$PWD/toolchain/proton-clang/bin:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          make a30s-defconfig
          make -j$(nproc)

      - name: Upload Boot Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-output
          path: |
            arch/arm64/boot/Image.gz-dtb
            arch/arm64/boot/Image
            arch/arm64/boot/dts
